---
title: HackPrinceton Fall 2017 | November 10-12, 2017
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Princeton University's 36-hour student hackathon. Learn, build, and explore
  software and hardware with 600 fellow students this November 10-12.
baseurl: 
incremental: true
gems:
- jekyll-redirect-from
